// generated by Fast Light User Interface Designer (fluid) version 1.0305

#ifndef UserInterface_h
#define UserInterface_h
#include <FL/Fl.H>
#include "UserInterfaceItems.h"
#include <FL/Fl_Pack.H>
#include <FL/Fl_Group.H>
#include "ToolButton.h"
#include <FL/Fl_Value_Output.H>
#include <FL/Fl_Check_Button.H>
#include <FL/Fl_Value_Input.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Scrollbar.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Value_Slider.H>
#include <FL/Fl_Round_Button.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Return_Button.H>
#include <FL/Fl_Spinner.H>
#include <FL/Fl_Light_Button.H>
#include <FL/Fl_Tabs.H>
#include "CoordinateSelector.h"
#include <FL/Fl_Progress.H>
#include <FL/Fl_Slider.H>
#include <FL/Fl_Help_View.H>

class UserInterface {
public:
  void make_windows();
  SocietyWindow *societyWindow;
  static Fl_Menu_Item menu_societyWindow[];
private:
  inline void cb_New_i(Fl_Menu_*, void*);
  static void cb_New(Fl_Menu_*, void*);
  inline void cb_Open_i(Fl_Menu_*, void*);
  static void cb_Open(Fl_Menu_*, void*);
  inline void cb_Save_i(Fl_Menu_*, void*);
  static void cb_Save(Fl_Menu_*, void*);
  inline void cb_Save1_i(Fl_Menu_*, void*);
  static void cb_Save1(Fl_Menu_*, void*);
  inline void cb_Pajek_i(Fl_Menu_*, void*);
  static void cb_Pajek(Fl_Menu_*, void*);
  inline void cb_Quit_i(Fl_Menu_*, void*);
  static void cb_Quit(Fl_Menu_*, void*);
  inline void cb_Undo_i(Fl_Menu_*, void*);
  static void cb_Undo(Fl_Menu_*, void*);
  inline void cb_Redo_i(Fl_Menu_*, void*);
  static void cb_Redo(Fl_Menu_*, void*);
  inline void cb_Cut_i(Fl_Menu_*, void*);
  static void cb_Cut(Fl_Menu_*, void*);
  inline void cb_Copy_i(Fl_Menu_*, void*);
  static void cb_Copy(Fl_Menu_*, void*);
  inline void cb_Paste_i(Fl_Menu_*, void*);
  static void cb_Paste(Fl_Menu_*, void*);
  inline void cb_Delete_i(Fl_Menu_*, void*);
  static void cb_Delete(Fl_Menu_*, void*);
  inline void cb_Select_i(Fl_Menu_*, void*);
  static void cb_Select(Fl_Menu_*, void*);
  inline void cb_Deselect_i(Fl_Menu_*, void*);
  static void cb_Deselect(Fl_Menu_*, void*);
  inline void cb_Interactive_i(Fl_Menu_*, void*);
  static void cb_Interactive(Fl_Menu_*, void*);
  inline void cb_Batch_i(Fl_Menu_*, void*);
  static void cb_Batch(Fl_Menu_*, void*);
  inline void cb_Multibatch_i(Fl_Menu_*, void*);
  static void cb_Multibatch(Fl_Menu_*, void*);
  inline void cb_Generate_i(Fl_Menu_*, void*);
  static void cb_Generate(Fl_Menu_*, void*);
  inline void cb_Randomise_i(Fl_Menu_*, void*);
  static void cb_Randomise(Fl_Menu_*, void*);
  inline void cb_Society_i(Fl_Menu_*, void*);
  static void cb_Society(Fl_Menu_*, void*);
  inline void cb_Inquirer_i(Fl_Menu_*, void*);
  static void cb_Inquirer(Fl_Menu_*, void*);
  inline void cb_Link_i(Fl_Menu_*, void*);
  static void cb_Link(Fl_Menu_*, void*);
  inline void cb_About_i(Fl_Menu_*, void*);
  static void cb_About(Fl_Menu_*, void*);
  inline void cb_Manual_i(Fl_Menu_*, void*);
  static void cb_Manual(Fl_Menu_*, void*);
  inline void cb_Tooltips_i(Fl_Menu_*, void*);
  static void cb_Tooltips(Fl_Menu_*, void*);
  inline void cb_societyWindow_i(ToolButton*, void*);
  static void cb_societyWindow(ToolButton*, void*);
  static Fl_Menu_Item menu_societyWindow1[];
  inline void cb_Select1_i(Fl_Menu_*, void*);
  static void cb_Select1(Fl_Menu_*, void*);
  inline void cb_Select2_i(Fl_Menu_*, void*);
  static void cb_Select2(Fl_Menu_*, void*);
  inline void cb_Select3_i(Fl_Menu_*, void*);
  static void cb_Select3(Fl_Menu_*, void*);
  inline void cb_societyWindow1_i(ToolButton*, void*);
  static void cb_societyWindow1(ToolButton*, void*);
  static Fl_Menu_Item menu_societyWindow2[];
  inline void cb_Set_i(Fl_Menu_*, void*);
  static void cb_Set(Fl_Menu_*, void*);
  inline void cb_societyWindow2_i(ToolButton*, void*);
  static void cb_societyWindow2(ToolButton*, void*);
  static Fl_Menu_Item menu_societyWindow3[];
  inline void cb_Set1_i(Fl_Menu_*, void*);
  static void cb_Set1(Fl_Menu_*, void*);
  inline void cb_Show_i(Fl_Check_Button*, void*);
  static void cb_Show(Fl_Check_Button*, void*);
  inline void cb_societyWindow3_i(Fl_Value_Input*, void*);
  static void cb_societyWindow3(Fl_Value_Input*, void*);
  inline void cb_societyWindow4_i(Fl_Button*, void*);
  static void cb_societyWindow4(Fl_Button*, void*);
  inline void cb_societyWindow5_i(Fl_Button*, void*);
  static void cb_societyWindow5(Fl_Button*, void*);
  inline void cb_societyWindow6_i(Fl_Button*, void*);
  static void cb_societyWindow6(Fl_Button*, void*);
  inline void cb_societyWindow7_i(Fl_Button*, void*);
  static void cb_societyWindow7(Fl_Button*, void*);
  inline void cb_societyWindow8_i(Fl_Button*, void*);
  static void cb_societyWindow8(Fl_Button*, void*);
  inline void cb_Show1_i(Fl_Check_Button*, void*);
  static void cb_Show1(Fl_Check_Button*, void*);
  inline void cb_Show2_i(Fl_Check_Button*, void*);
  static void cb_Show2(Fl_Check_Button*, void*);
  inline void cb_societyWindow9_i(Fl_Scrollbar*, void*);
  static void cb_societyWindow9(Fl_Scrollbar*, void*);
  inline void cb_societyWindowa_i(Fl_Scrollbar*, void*);
  static void cb_societyWindowa(Fl_Scrollbar*, void*);
public:
  InquirerWindow *inquirerWindow;
private:
  inline void cb_inquirerWindow_i(Fl_Input*, void*);
  static void cb_inquirerWindow(Fl_Input*, void*);
  inline void cb_inquirerWindow1_i(Fl_Value_Slider*, void*);
  static void cb_inquirerWindow1(Fl_Value_Slider*, void*);
  inline void cb_inquirerWindow2_i(Fl_Value_Slider*, void*);
  static void cb_inquirerWindow2(Fl_Value_Slider*, void*);
  inline void cb_inquirerWindow3_i(Fl_Value_Slider*, void*);
  static void cb_inquirerWindow3(Fl_Value_Slider*, void*);
  inline void cb_inquirerWindow4_i(Fl_Button*, void*);
  static void cb_inquirerWindow4(Fl_Button*, void*);
  inline void cb_inquirerWindow5_i(TrustView*, void*);
  static void cb_inquirerWindow5(TrustView*, void*);
  inline void cb_inquirerWindow6_i(Fl_Check_Button*, void*);
  static void cb_inquirerWindow6(Fl_Check_Button*, void*);
  inline void cb_returnarrow_i(Fl_Button*, void*);
  static void cb_returnarrow(Fl_Button*, void*);
  inline void cb_returnarrow1_i(Fl_Button*, void*);
  static void cb_returnarrow1(Fl_Button*, void*);
  inline void cb_returnarrow2_i(Fl_Button*, void*);
  static void cb_returnarrow2(Fl_Button*, void*);
  inline void cb_inquirerWindow7_i(Fl_Check_Button*, void*);
  static void cb_inquirerWindow7(Fl_Check_Button*, void*);
  inline void cb_inquirerWindow8_i(Fl_Check_Button*, void*);
  static void cb_inquirerWindow8(Fl_Check_Button*, void*);
  inline void cb__i(Fl_Button*, void*);
  static void cb_(Fl_Button*, void*);
public:
  LinkWindow *linkWindow;
private:
  inline void cb_linkWindow_i(Fl_Value_Slider*, void*);
  static void cb_linkWindow(Fl_Value_Slider*, void*);
  inline void cb_linkWindow1_i(Fl_Button*, void*);
  static void cb_linkWindow1(Fl_Button*, void*);
  inline void cb_linkWindow2_i(Fl_Value_Slider*, void*);
  static void cb_linkWindow2(Fl_Value_Slider*, void*);
  inline void cb_linkWindow3_i(TrustView*, void*);
  static void cb_linkWindow3(TrustView*, void*);
  inline void cb_linkWindow4_i(Fl_Check_Button*, void*);
  static void cb_linkWindow4(Fl_Check_Button*, void*);
  inline void cb_returnarrow3_i(Fl_Button*, void*);
  static void cb_returnarrow3(Fl_Button*, void*);
  inline void cb_returnarrow4_i(Fl_Button*, void*);
  static void cb_returnarrow4(Fl_Button*, void*);
  inline void cb_linkWindow5_i(Fl_Round_Button*, void*);
  static void cb_linkWindow5(Fl_Round_Button*, void*);
  inline void cb_linkWindow6_i(Fl_Round_Button*, void*);
  static void cb_linkWindow6(Fl_Round_Button*, void*);
  inline void cb_linkWindow7_i(Fl_Round_Button*, void*);
  static void cb_linkWindow7(Fl_Round_Button*, void*);
  inline void cb_linkWindow8_i(Fl_Check_Button*, void*);
  static void cb_linkWindow8(Fl_Check_Button*, void*);
  inline void cb_linkWindow9_i(Fl_Check_Button*, void*);
  static void cb_linkWindow9(Fl_Check_Button*, void*);
  inline void cb_1_i(Fl_Button*, void*);
  static void cb_1(Fl_Button*, void*);
public:
  SimulationWindow *simulationWindow;
private:
  inline void cb_simulationWindow_i(Fl_Button*, void*);
  static void cb_simulationWindow(Fl_Button*, void*);
  inline void cb_simulationWindow1_i(Fl_Button*, void*);
  static void cb_simulationWindow1(Fl_Button*, void*);
  inline void cb_simulationWindow2_i(Fl_Button*, void*);
  static void cb_simulationWindow2(Fl_Button*, void*);
  static Fl_Menu_Item menu_simulationWindow[];
  inline void cb_None_i(Fl_Menu_*, void*);
  static void cb_None(Fl_Menu_*, void*);
  inline void cb_Summary_i(Fl_Menu_*, void*);
  static void cb_Summary(Fl_Menu_*, void*);
  inline void cb_Standard_i(Fl_Menu_*, void*);
  static void cb_Standard(Fl_Menu_*, void*);
  inline void cb_Detailed_i(Fl_Menu_*, void*);
  static void cb_Detailed(Fl_Menu_*, void*);
  inline void cb_Cancel_i(Fl_Button*, void*);
  static void cb_Cancel(Fl_Button*, void*);
  inline void cb_simulationWindow3_i(Fl_Button*, void*);
  static void cb_simulationWindow3(Fl_Button*, void*);
public:
  Fl_Return_Button *Apply;
private:
  inline void cb_Apply_i(Fl_Return_Button*, void*);
  static void cb_Apply(Fl_Return_Button*, void*);
  inline void cb_2_i(Fl_Button*, void*);
  static void cb_2(Fl_Button*, void*);
public:
  DistributionWindow *distributionWindow;
private:
  inline void cb_OK_i(Fl_Return_Button*, void*);
  static void cb_OK(Fl_Return_Button*, void*);
  inline void cb_Cancel1_i(Fl_Button*, void*);
  static void cb_Cancel1(Fl_Button*, void*);
  static Fl_Menu_Item menu_distributionWindow[];
  inline void cb_Combined_i(Fl_Menu_*, void*);
  static void cb_Combined(Fl_Menu_*, void*);
  inline void cb_Point_i(Fl_Menu_*, void*);
  static void cb_Point(Fl_Menu_*, void*);
  inline void cb_Interval_i(Fl_Menu_*, void*);
  static void cb_Interval(Fl_Menu_*, void*);
  inline void cb_Normal_i(Fl_Menu_*, void*);
  static void cb_Normal(Fl_Menu_*, void*);
  inline void cb_Beta_i(Fl_Menu_*, void*);
  static void cb_Beta(Fl_Menu_*, void*);
  inline void cb_Freeform_i(Fl_Menu_*, void*);
  static void cb_Freeform(Fl_Menu_*, void*);
  inline void cb_distributionWindow_i(Fl_Button*, void*);
  static void cb_distributionWindow(Fl_Button*, void*);
  inline void cb_distributionWindow1_i(Fl_Button*, void*);
  static void cb_distributionWindow1(Fl_Button*, void*);
  inline void cb_distributionWindow2_i(Fl_Value_Slider*, void*);
  static void cb_distributionWindow2(Fl_Value_Slider*, void*);
  inline void cb_returnarrow5_i(Fl_Button*, void*);
  static void cb_returnarrow5(Fl_Button*, void*);
  inline void cb_returnarrow6_i(Fl_Button*, void*);
  static void cb_returnarrow6(Fl_Button*, void*);
  inline void cb_distributionWindow3_i(Fl_Value_Slider*, void*);
  static void cb_distributionWindow3(Fl_Value_Slider*, void*);
  inline void cb_distributionWindow4_i(Fl_Value_Slider*, void*);
  static void cb_distributionWindow4(Fl_Value_Slider*, void*);
  inline void cb_returnarrow7_i(Fl_Button*, void*);
  static void cb_returnarrow7(Fl_Button*, void*);
  inline void cb_returnarrow8_i(Fl_Button*, void*);
  static void cb_returnarrow8(Fl_Button*, void*);
  inline void cb_distributionWindow5_i(Fl_Value_Slider*, void*);
  static void cb_distributionWindow5(Fl_Value_Slider*, void*);
  inline void cb_distributionWindow6_i(Fl_Value_Slider*, void*);
  static void cb_distributionWindow6(Fl_Value_Slider*, void*);
  inline void cb_returnarrow9_i(Fl_Button*, void*);
  static void cb_returnarrow9(Fl_Button*, void*);
  inline void cb_distributionWindow7_i(Fl_Value_Slider*, void*);
  static void cb_distributionWindow7(Fl_Value_Slider*, void*);
  inline void cb_returnarrowa_i(Fl_Button*, void*);
  static void cb_returnarrowa(Fl_Button*, void*);
  inline void cb_returnarrowb_i(Fl_Button*, void*);
  static void cb_returnarrowb(Fl_Button*, void*);
  inline void cb_distributionWindow8_i(Fl_Value_Slider*, void*);
  static void cb_distributionWindow8(Fl_Value_Slider*, void*);
  inline void cb_distributionWindow9_i(Fl_Value_Slider*, void*);
  static void cb_distributionWindow9(Fl_Value_Slider*, void*);
  inline void cb_returnarrowc_i(Fl_Button*, void*);
  static void cb_returnarrowc(Fl_Button*, void*);
  inline void cb_distributionWindowa_i(Fl_Value_Slider*, void*);
  static void cb_distributionWindowa(Fl_Value_Slider*, void*);
  inline void cb_returnarrowd_i(Fl_Button*, void*);
  static void cb_returnarrowd(Fl_Button*, void*);
  inline void cb_returnarrowe_i(Fl_Button*, void*);
  static void cb_returnarrowe(Fl_Button*, void*);
  inline void cb_distributionWindowb_i(Fl_Value_Slider*, void*);
  static void cb_distributionWindowb(Fl_Value_Slider*, void*);
  inline void cb_distributionWindowc_i(Fl_Value_Slider*, void*);
  static void cb_distributionWindowc(Fl_Value_Slider*, void*);
  inline void cb_returnarrowf_i(Fl_Button*, void*);
  static void cb_returnarrowf(Fl_Button*, void*);
  inline void cb_returnarrow10_i(Fl_Button*, void*);
  static void cb_returnarrow10(Fl_Button*, void*);
  inline void cb_distributionWindowd_i(Fl_Value_Slider*, void*);
  static void cb_distributionWindowd(Fl_Value_Slider*, void*);
  inline void cb_distributionWindowe_i(Fl_Button*, void*);
  static void cb_distributionWindowe(Fl_Button*, void*);
  inline void cb_3_i(Fl_Button*, void*);
  static void cb_3(Fl_Button*, void*);
  inline void cb_4_i(Fl_Button*, void*);
  static void cb_4(Fl_Button*, void*);
  inline void cb_Clear_i(Fl_Button*, void*);
  static void cb_Clear(Fl_Button*, void*);
  inline void cb_Set2_i(Fl_Button*, void*);
  static void cb_Set2(Fl_Button*, void*);
  inline void cb_distributionWindowf_i(Fl_Spinner*, void*);
  static void cb_distributionWindowf(Fl_Spinner*, void*);
  inline void cb_5_i(Fl_Button*, void*);
  static void cb_5(Fl_Button*, void*);
  inline void cb_6_i(Fl_Button*, void*);
  static void cb_6(Fl_Button*, void*);
  inline void cb_7_i(Fl_Button*, void*);
  static void cb_7(Fl_Button*, void*);
  inline void cb_8_i(Fl_Button*, void*);
  static void cb_8(Fl_Button*, void*);
  inline void cb_9_i(Fl_Button*, void*);
  static void cb_9(Fl_Button*, void*);
  inline void cb_distributionWindow10_i(Fl_Light_Button*, void*);
  static void cb_distributionWindow10(Fl_Light_Button*, void*);
  inline void cb_distributionWindow11_i(Fl_Light_Button*, void*);
  static void cb_distributionWindow11(Fl_Light_Button*, void*);
  inline void cb_a_i(Fl_Button*, void*);
  static void cb_a(Fl_Button*, void*);
public:
  CreateInquirerPrefsWindow *createInquirerPrefsWindow;
private:
  inline void cb_OK1_i(Fl_Return_Button*, void*);
  static void cb_OK1(Fl_Return_Button*, void*);
  inline void cb_Cancel2_i(Fl_Button*, void*);
  static void cb_Cancel2(Fl_Button*, void*);
  inline void cb_createInquirerPrefsWindow_i(Fl_Check_Button*, void*);
  static void cb_createInquirerPrefsWindow(Fl_Check_Button*, void*);
  inline void cb_createInquirerPrefsWindow1_i(DistributionView*, void*);
  static void cb_createInquirerPrefsWindow1(DistributionView*, void*);
  inline void cb_createInquirerPrefsWindow2_i(DistributionView*, void*);
  static void cb_createInquirerPrefsWindow2(DistributionView*, void*);
  inline void cb_createInquirerPrefsWindow3_i(MetaDistributionView*, void*);
  static void cb_createInquirerPrefsWindow3(MetaDistributionView*, void*);
  inline void cb_createInquirerPrefsWindow4_i(DistributionView*, void*);
  static void cb_createInquirerPrefsWindow4(DistributionView*, void*);
  inline void cb_createInquirerPrefsWindow5_i(Fl_Check_Button*, void*);
  static void cb_createInquirerPrefsWindow5(Fl_Check_Button*, void*);
public:
  CreateLinkPrefsWindow *createLinkPrefsWindow;
private:
  inline void cb_OK2_i(Fl_Return_Button*, void*);
  static void cb_OK2(Fl_Return_Button*, void*);
  inline void cb_Cancel3_i(Fl_Button*, void*);
  static void cb_Cancel3(Fl_Button*, void*);
  inline void cb_createLinkPrefsWindow_i(DistributionView*, void*);
  static void cb_createLinkPrefsWindow(DistributionView*, void*);
  inline void cb_createLinkPrefsWindow1_i(DistributionView*, void*);
  static void cb_createLinkPrefsWindow1(DistributionView*, void*);
  inline void cb_createLinkPrefsWindow2_i(MetaDistributionView*, void*);
  static void cb_createLinkPrefsWindow2(MetaDistributionView*, void*);
  inline void cb_createLinkPrefsWindow3_i(Fl_Check_Button*, void*);
  static void cb_createLinkPrefsWindow3(Fl_Check_Button*, void*);
  inline void cb_createLinkPrefsWindow4_i(Fl_Round_Button*, void*);
  static void cb_createLinkPrefsWindow4(Fl_Round_Button*, void*);
  inline void cb_createLinkPrefsWindow5_i(Fl_Round_Button*, void*);
  static void cb_createLinkPrefsWindow5(Fl_Round_Button*, void*);
  inline void cb_createLinkPrefsWindow6_i(Fl_Round_Button*, void*);
  static void cb_createLinkPrefsWindow6(Fl_Round_Button*, void*);
  inline void cb_createLinkPrefsWindow7_i(Fl_Check_Button*, void*);
  static void cb_createLinkPrefsWindow7(Fl_Check_Button*, void*);
public:
  BatchSimulationWindow *batchSimulationWindow;
private:
  inline void cb_batchSimulationWindow_i(Fl_Button*, void*);
  static void cb_batchSimulationWindow(Fl_Button*, void*);
  inline void cb_OK3_i(Fl_Return_Button*, void*);
  static void cb_OK3(Fl_Return_Button*, void*);
  inline void cb_batchSimulationWindow1_i(Fl_Button*, void*);
  static void cb_batchSimulationWindow1(Fl_Button*, void*);
  inline void cb_batchSimulationWindow2_i(Fl_Button*, void*);
  static void cb_batchSimulationWindow2(Fl_Button*, void*);
  inline void cb_batchSimulationWindow3_i(Fl_Value_Input*, void*);
  static void cb_batchSimulationWindow3(Fl_Value_Input*, void*);
  inline void cb_batchSimulationWindow4_i(Fl_Check_Button*, void*);
  static void cb_batchSimulationWindow4(Fl_Check_Button*, void*);
  inline void cb_batchSimulationWindow5_i(Fl_Value_Input*, void*);
  static void cb_batchSimulationWindow5(Fl_Value_Input*, void*);
  inline void cb_batchSimulationWindow6_i(Fl_Value_Input*, void*);
  static void cb_batchSimulationWindow6(Fl_Value_Input*, void*);
  inline void cb_batchSimulationWindow7_i(Fl_Check_Button*, void*);
  static void cb_batchSimulationWindow7(Fl_Check_Button*, void*);
  inline void cb_batchSimulationWindow8_i(DistributionView*, void*);
  static void cb_batchSimulationWindow8(DistributionView*, void*);
  inline void cb_batchSimulationWindow9_i(DistributionView*, void*);
  static void cb_batchSimulationWindow9(DistributionView*, void*);
  inline void cb_batchSimulationWindowa_i(Fl_Check_Button*, void*);
  static void cb_batchSimulationWindowa(Fl_Check_Button*, void*);
  inline void cb_batchSimulationWindowb_i(Fl_Value_Input*, void*);
  static void cb_batchSimulationWindowb(Fl_Value_Input*, void*);
  inline void cb_batchSimulationWindowc_i(Fl_Value_Input*, void*);
  static void cb_batchSimulationWindowc(Fl_Value_Input*, void*);
  inline void cb_batchSimulationWindowd_i(Fl_Value_Input*, void*);
  static void cb_batchSimulationWindowd(Fl_Value_Input*, void*);
  inline void cb_batchSimulationWindowe_i(Fl_Value_Input*, void*);
  static void cb_batchSimulationWindowe(Fl_Value_Input*, void*);
  static Fl_Menu_Item menu_batchSimulationWindow[];
  inline void cb_in_i(Fl_Menu_*, void*);
  static void cb_in(Fl_Menu_*, void*);
  inline void cb_per_i(Fl_Menu_*, void*);
  static void cb_per(Fl_Menu_*, void*);
  inline void cb_per1_i(Fl_Menu_*, void*);
  static void cb_per1(Fl_Menu_*, void*);
  inline void cb_batchSimulationWindowf_i(Fl_Value_Slider*, void*);
  static void cb_batchSimulationWindowf(Fl_Value_Slider*, void*);
  inline void cb_batchSimulationWindow10_i(Fl_Value_Slider*, void*);
  static void cb_batchSimulationWindow10(Fl_Value_Slider*, void*);
  inline void cb_batchSimulationWindow11_i(Fl_Check_Button*, void*);
  static void cb_batchSimulationWindow11(Fl_Check_Button*, void*);
  static Fl_Menu_Item menu_batchSimulationWindow1[];
  inline void cb_Density_i(Fl_Menu_*, void*);
  static void cb_Density(Fl_Menu_*, void*);
  inline void cb_Number_i(Fl_Menu_*, void*);
  static void cb_Number(Fl_Menu_*, void*);
  inline void cb_batchSimulationWindow12_i(Fl_Check_Button*, void*);
  static void cb_batchSimulationWindow12(Fl_Check_Button*, void*);
  inline void cb_batchSimulationWindow13_i(DistributionView*, void*);
  static void cb_batchSimulationWindow13(DistributionView*, void*);
  inline void cb_batchSimulationWindow14_i(Fl_Check_Button*, void*);
  static void cb_batchSimulationWindow14(Fl_Check_Button*, void*);
  inline void cb_batchSimulationWindow15_i(DistributionView*, void*);
  static void cb_batchSimulationWindow15(DistributionView*, void*);
  inline void cb_batchSimulationWindow16_i(Fl_Check_Button*, void*);
  static void cb_batchSimulationWindow16(Fl_Check_Button*, void*);
  inline void cb_batchSimulationWindow17_i(MetaDistributionView*, void*);
  static void cb_batchSimulationWindow17(MetaDistributionView*, void*);
  inline void cb_batchSimulationWindow18_i(DistributionView*, void*);
  static void cb_batchSimulationWindow18(DistributionView*, void*);
  inline void cb_batchSimulationWindow19_i(Fl_Check_Button*, void*);
  static void cb_batchSimulationWindow19(Fl_Check_Button*, void*);
  inline void cb_batchSimulationWindow1a_i(Fl_Check_Button*, void*);
  static void cb_batchSimulationWindow1a(Fl_Check_Button*, void*);
  inline void cb_batchSimulationWindow1b_i(DistributionView*, void*);
  static void cb_batchSimulationWindow1b(DistributionView*, void*);
  inline void cb_batchSimulationWindow1c_i(Fl_Check_Button*, void*);
  static void cb_batchSimulationWindow1c(Fl_Check_Button*, void*);
  inline void cb_batchSimulationWindow1d_i(DistributionView*, void*);
  static void cb_batchSimulationWindow1d(DistributionView*, void*);
  inline void cb_batchSimulationWindow1e_i(Fl_Check_Button*, void*);
  static void cb_batchSimulationWindow1e(Fl_Check_Button*, void*);
  inline void cb_batchSimulationWindow1f_i(MetaDistributionView*, void*);
  static void cb_batchSimulationWindow1f(MetaDistributionView*, void*);
  inline void cb_batchSimulationWindow20_i(Fl_Round_Button*, void*);
  static void cb_batchSimulationWindow20(Fl_Round_Button*, void*);
  inline void cb_batchSimulationWindow21_i(Fl_Round_Button*, void*);
  static void cb_batchSimulationWindow21(Fl_Round_Button*, void*);
  inline void cb_batchSimulationWindow22_i(Fl_Round_Button*, void*);
  static void cb_batchSimulationWindow22(Fl_Round_Button*, void*);
  inline void cb_batchSimulationWindow23_i(Fl_Check_Button*, void*);
  static void cb_batchSimulationWindow23(Fl_Check_Button*, void*);
  inline void cb_batchSimulationWindow24_i(Fl_Round_Button*, void*);
  static void cb_batchSimulationWindow24(Fl_Round_Button*, void*);
  inline void cb_batchSimulationWindow25_i(Fl_Round_Button*, void*);
  static void cb_batchSimulationWindow25(Fl_Round_Button*, void*);
  inline void cb_batchSimulationWindow26_i(Fl_Value_Input*, void*);
  static void cb_batchSimulationWindow26(Fl_Value_Input*, void*);
  inline void cb_batchSimulationWindow27_i(Fl_Value_Input*, void*);
  static void cb_batchSimulationWindow27(Fl_Value_Input*, void*);
  inline void cb_batchSimulationWindow28_i(Fl_Round_Button*, void*);
  static void cb_batchSimulationWindow28(Fl_Round_Button*, void*);
  inline void cb_batchSimulationWindow29_i(Fl_Button*, void*);
  static void cb_batchSimulationWindow29(Fl_Button*, void*);
  inline void cb_batchSimulationWindow2a_i(Fl_Button*, void*);
  static void cb_batchSimulationWindow2a(Fl_Button*, void*);
  inline void cb_batchSimulationWindow2b_i(Fl_Value_Input*, void*);
  static void cb_batchSimulationWindow2b(Fl_Value_Input*, void*);
  inline void cb_batchSimulationWindow2c_i(Fl_Button*, void*);
  static void cb_batchSimulationWindow2c(Fl_Button*, void*);
  inline void cb_batchSimulationWindow2d_i(Fl_Value_Input*, void*);
  static void cb_batchSimulationWindow2d(Fl_Value_Input*, void*);
  inline void cb_batchSimulationWindow2e_i(Fl_Value_Input*, void*);
  static void cb_batchSimulationWindow2e(Fl_Value_Input*, void*);
  inline void cb_batchSimulationWindow2f_i(Fl_Value_Input*, void*);
  static void cb_batchSimulationWindow2f(Fl_Value_Input*, void*);
  inline void cb_batchSimulationWindow30_i(Fl_Value_Input*, void*);
  static void cb_batchSimulationWindow30(Fl_Value_Input*, void*);
  inline void cb_batchSimulationWindow31_i(Fl_Check_Button*, void*);
  static void cb_batchSimulationWindow31(Fl_Check_Button*, void*);
  inline void cb_batchSimulationWindow32_i(Fl_Value_Input*, void*);
  static void cb_batchSimulationWindow32(Fl_Value_Input*, void*);
  inline void cb_batchSimulationWindow33_i(Fl_Value_Input*, void*);
  static void cb_batchSimulationWindow33(Fl_Value_Input*, void*);
  inline void cb_batchSimulationWindow34_i(Fl_Check_Button*, void*);
  static void cb_batchSimulationWindow34(Fl_Check_Button*, void*);
  inline void cb_batchSimulationWindow35_i(Fl_Value_Input*, void*);
  static void cb_batchSimulationWindow35(Fl_Value_Input*, void*);
  inline void cb_batchSimulationWindow36_i(Fl_Spinner*, void*);
  static void cb_batchSimulationWindow36(Fl_Spinner*, void*);
  inline void cb_batchSimulationWindow37_i(Fl_Button*, void*);
  static void cb_batchSimulationWindow37(Fl_Button*, void*);
  inline void cb_batchSimulationWindow38_i(Fl_Button*, void*);
  static void cb_batchSimulationWindow38(Fl_Button*, void*);
  inline void cb_batchSimulationWindow39_i(Fl_Button*, void*);
  static void cb_batchSimulationWindow39(Fl_Button*, void*);
  inline void cb_batchSimulationWindow3a_i(Fl_Button*, void*);
  static void cb_batchSimulationWindow3a(Fl_Button*, void*);
  inline void cb_batchSimulationWindow3b_i(Fl_Button*, void*);
  static void cb_batchSimulationWindow3b(Fl_Button*, void*);
  inline void cb_batchSimulationWindow3c_i(Fl_Button*, void*);
  static void cb_batchSimulationWindow3c(Fl_Button*, void*);
  inline void cb_batchSimulationWindow3d_i(Fl_Light_Button*, void*);
  static void cb_batchSimulationWindow3d(Fl_Light_Button*, void*);
  inline void cb_batchSimulationWindow3e_i(Fl_Light_Button*, void*);
  static void cb_batchSimulationWindow3e(Fl_Light_Button*, void*);
  inline void cb_batchSimulationWindow3f_i(Fl_Light_Button*, void*);
  static void cb_batchSimulationWindow3f(Fl_Light_Button*, void*);
  inline void cb_batchSimulationWindow40_i(Fl_Light_Button*, void*);
  static void cb_batchSimulationWindow40(Fl_Light_Button*, void*);
  inline void cb_batchSimulationWindow41_i(Fl_Value_Input*, void*);
  static void cb_batchSimulationWindow41(Fl_Value_Input*, void*);
  inline void cb_batchSimulationWindow42_i(CoordinateSelector*, void*);
  static void cb_batchSimulationWindow42(CoordinateSelector*, void*);
  inline void cb_b_i(Fl_Button*, void*);
  static void cb_b(Fl_Button*, void*);
public:
  ProgressWindow *progressWindow;
private:
  inline void cb_Cancel4_i(Fl_Button*, void*);
  static void cb_Cancel4(Fl_Button*, void*);
public:
  StatisticsWindow *statisticsWindow;
private:
  inline void cb_Close_i(Fl_Button*, void*);
  static void cb_Close(Fl_Button*, void*);
  static Fl_Menu_Item menu_statisticsWindow[];
  inline void cb_90_i(Fl_Menu_*, void*);
  static void cb_90(Fl_Menu_*, void*);
  inline void cb_95_i(Fl_Menu_*, void*);
  static void cb_95(Fl_Menu_*, void*);
  inline void cb_99_i(Fl_Menu_*, void*);
  static void cb_99(Fl_Menu_*, void*);
  inline void cb_991_i(Fl_Menu_*, void*);
  static void cb_991(Fl_Menu_*, void*);
  inline void cb_c_i(Fl_Button*, void*);
  static void cb_c(Fl_Button*, void*);
  inline void cb_View_i(Fl_Button*, void*);
  static void cb_View(Fl_Button*, void*);
  inline void cb_statisticsWindow_i(Fl_Button*, void*);
  static void cb_statisticsWindow(Fl_Button*, void*);
  inline void cb_statisticsWindow1_i(Fl_Choice*, void*);
  static void cb_statisticsWindow1(Fl_Choice*, void*);
  static Fl_Menu_Item menu_statisticsWindow1[];
  inline void cb_statisticsWindow2_i(Fl_Button*, void*);
  static void cb_statisticsWindow2(Fl_Button*, void*);
public:
  AboutWindow *aboutWindow;
private:
  inline void cb_aboutWindow_i(Fl_Button*, void*);
  static void cb_aboutWindow(Fl_Button*, void*);
public:
  InquirerParametersWindow *inquirerParametersWindow;
private:
  inline void cb_OK4_i(Fl_Return_Button*, void*);
  static void cb_OK4(Fl_Return_Button*, void*);
  inline void cb_Cancel5_i(Fl_Button*, void*);
  static void cb_Cancel5(Fl_Button*, void*);
  inline void cb_inquirerParametersWindow_i(Fl_Slider*, void*);
  static void cb_inquirerParametersWindow(Fl_Slider*, void*);
  inline void cb_inquirerParametersWindow1_i(Fl_Slider*, void*);
  static void cb_inquirerParametersWindow1(Fl_Slider*, void*);
  inline void cb_inquirerParametersWindow2_i(Fl_Slider*, void*);
  static void cb_inquirerParametersWindow2(Fl_Slider*, void*);
  inline void cb_inquirerParametersWindow3_i(DistributionView*, void*);
  static void cb_inquirerParametersWindow3(DistributionView*, void*);
  inline void cb_inquirerParametersWindow4_i(DistributionView*, void*);
  static void cb_inquirerParametersWindow4(DistributionView*, void*);
  inline void cb_inquirerParametersWindow5_i(MetaDistributionView*, void*);
  static void cb_inquirerParametersWindow5(MetaDistributionView*, void*);
  inline void cb_inquirerParametersWindow6_i(DistributionView*, void*);
  static void cb_inquirerParametersWindow6(DistributionView*, void*);
  inline void cb_inquirerParametersWindow7_i(Fl_Slider*, void*);
  static void cb_inquirerParametersWindow7(Fl_Slider*, void*);
  inline void cb_d_i(Fl_Button*, void*);
  static void cb_d(Fl_Button*, void*);
public:
  LinkParametersWindow *linkParametersWindow;
private:
  inline void cb_OK5_i(Fl_Return_Button*, void*);
  static void cb_OK5(Fl_Return_Button*, void*);
  inline void cb_Cancel6_i(Fl_Button*, void*);
  static void cb_Cancel6(Fl_Button*, void*);
  inline void cb_linkParametersWindow_i(Fl_Slider*, void*);
  static void cb_linkParametersWindow(Fl_Slider*, void*);
  inline void cb_linkParametersWindow1_i(Fl_Slider*, void*);
  static void cb_linkParametersWindow1(Fl_Slider*, void*);
  inline void cb_linkParametersWindow2_i(DistributionView*, void*);
  static void cb_linkParametersWindow2(DistributionView*, void*);
  inline void cb_linkParametersWindow3_i(DistributionView*, void*);
  static void cb_linkParametersWindow3(DistributionView*, void*);
  inline void cb_linkParametersWindow4_i(MetaDistributionView*, void*);
  static void cb_linkParametersWindow4(MetaDistributionView*, void*);
  inline void cb_linkParametersWindow5_i(Fl_Slider*, void*);
  static void cb_linkParametersWindow5(Fl_Slider*, void*);
  inline void cb_e_i(Fl_Button*, void*);
  static void cb_e(Fl_Button*, void*);
public:
  DistributionFreeformValuesWindow *distributionFreeformValuesWindow;
private:
  inline void cb_Set3_i(Fl_Return_Button*, void*);
  static void cb_Set3(Fl_Return_Button*, void*);
  inline void cb_distributionFreeformValuesWindow_i(Fl_Multi_Browser*, void*);
  static void cb_distributionFreeformValuesWindow(Fl_Multi_Browser*, void*);
  inline void cb_Done_i(Fl_Button*, void*);
  static void cb_Done(Fl_Button*, void*);
public:
  MetaDistributionWindow *metaDistributionWindow;
private:
  inline void cb_OK6_i(Fl_Return_Button*, void*);
  static void cb_OK6(Fl_Return_Button*, void*);
  inline void cb_Cancel7_i(Fl_Button*, void*);
  static void cb_Cancel7(Fl_Button*, void*);
  inline void cb_metaDistributionWindow_i(DistributionView*, void*);
  static void cb_metaDistributionWindow(DistributionView*, void*);
  inline void cb_metaDistributionWindow1_i(DistributionView*, void*);
  static void cb_metaDistributionWindow1(DistributionView*, void*);
  inline void cb_metaDistributionWindow2_i(DistributionView*, void*);
  static void cb_metaDistributionWindow2(DistributionView*, void*);
  inline void cb_metaDistributionWindow3_i(Fl_Slider*, void*);
  static void cb_metaDistributionWindow3(Fl_Slider*, void*);
  inline void cb_f_i(Fl_Button*, void*);
  static void cb_f(Fl_Button*, void*);
public:
  SetValuesWindow *setValuesWindow;
private:
  inline void cb_Set4_i(Fl_Return_Button*, void*);
  static void cb_Set4(Fl_Return_Button*, void*);
  inline void cb_Cancel8_i(Fl_Button*, void*);
  static void cb_Cancel8(Fl_Button*, void*);
public:
  MultiBatchWindow *multiBatchWindow;
private:
  inline void cb_OK7_i(Fl_Return_Button*, void*);
  static void cb_OK7(Fl_Return_Button*, void*);
  inline void cb_Cancel9_i(Fl_Button*, void*);
  static void cb_Cancel9(Fl_Button*, void*);
  inline void cb_multiBatchWindow_i(Fl_Button*, void*);
  static void cb_multiBatchWindow(Fl_Button*, void*);
  inline void cb_multiBatchWindow1_i(Fl_Button*, void*);
  static void cb_multiBatchWindow1(Fl_Button*, void*);
  inline void cb_multiBatchWindow2_i(Fl_Button*, void*);
  static void cb_multiBatchWindow2(Fl_Button*, void*);
  inline void cb_multiBatchWindow3_i(Fl_Button*, void*);
  static void cb_multiBatchWindow3(Fl_Button*, void*);
  inline void cb_multiBatchWindow4_i(Fl_Button*, void*);
  static void cb_multiBatchWindow4(Fl_Button*, void*);
  inline void cb_multiBatchWindow5_i(Fl_Spinner*, void*);
  static void cb_multiBatchWindow5(Fl_Spinner*, void*);
  inline void cb_multiBatchWindow6_i(Fl_Spinner*, void*);
  static void cb_multiBatchWindow6(Fl_Spinner*, void*);
  inline void cb_multiBatchWindow7_i(Fl_Button*, void*);
  static void cb_multiBatchWindow7(Fl_Button*, void*);
  inline void cb_multiBatchWindow8_i(Fl_Button*, void*);
  static void cb_multiBatchWindow8(Fl_Button*, void*);
  inline void cb_multiBatchWindow9_i(Fl_Button*, void*);
  static void cb_multiBatchWindow9(Fl_Button*, void*);
  inline void cb_multiBatchWindowa_i(Fl_Button*, void*);
  static void cb_multiBatchWindowa(Fl_Button*, void*);
  inline void cb_multiBatchWindowb_i(Fl_Button*, void*);
  static void cb_multiBatchWindowb(Fl_Button*, void*);
  inline void cb_multiBatchWindowc_i(Fl_Button*, void*);
  static void cb_multiBatchWindowc(Fl_Button*, void*);
  inline void cb_multiBatchWindowd_i(Fl_Button*, void*);
  static void cb_multiBatchWindowd(Fl_Button*, void*);
  inline void cb_multiBatchWindowe_i(Fl_Light_Button*, void*);
  static void cb_multiBatchWindowe(Fl_Light_Button*, void*);
  inline void cb_multiBatchWindowf_i(Fl_Light_Button*, void*);
  static void cb_multiBatchWindowf(Fl_Light_Button*, void*);
  inline void cb_multiBatchWindow10_i(Fl_Button*, void*);
  static void cb_multiBatchWindow10(Fl_Button*, void*);
  inline void cb_Load_i(Fl_Button*, void*);
  static void cb_Load(Fl_Button*, void*);
  inline void cb_Save2_i(Fl_Button*, void*);
  static void cb_Save2(Fl_Button*, void*);
  inline void cb_10_i(Fl_Button*, void*);
  static void cb_10(Fl_Button*, void*);
public:
  DoubleProgressWindow *doubleProgressWindow;
private:
  inline void cb_Cancela_i(Fl_Button*, void*);
  static void cb_Cancela(Fl_Button*, void*);
public:
  ManualWindow *manualWindow;
private:
  inline void cb_manualWindow_i(Fl_Button*, void*);
  static void cb_manualWindow(Fl_Button*, void*);
  inline void cb_manualWindow1_i(Fl_Button*, void*);
  static void cb_manualWindow1(Fl_Button*, void*);
  inline void cb_manualWindow2_i(Fl_Button*, void*);
  static void cb_manualWindow2(Fl_Button*, void*);
public:
  DegreeDistributionWindow *degreeDistributionWindow;
private:
  inline void cb_degreeDistributionWindow_i(Fl_Choice*, void*);
  static void cb_degreeDistributionWindow(Fl_Choice*, void*);
  inline void cb_degreeDistributionWindow1_i(Fl_Value_Slider*, void*);
  static void cb_degreeDistributionWindow1(Fl_Value_Slider*, void*);
  inline void cb_Fit_i(Fl_Button*, void*);
  static void cb_Fit(Fl_Button*, void*);
  inline void cb_degreeDistributionWindow2_i(Fl_Choice*, void*);
  static void cb_degreeDistributionWindow2(Fl_Choice*, void*);
  inline void cb_degreeDistributionWindow3_i(Fl_Value_Slider*, void*);
  static void cb_degreeDistributionWindow3(Fl_Value_Slider*, void*);
  inline void cb_Fit1_i(Fl_Button*, void*);
  static void cb_Fit1(Fl_Button*, void*);
  inline void cb_degreeDistributionWindow4_i(Fl_Choice*, void*);
  static void cb_degreeDistributionWindow4(Fl_Choice*, void*);
  inline void cb_degreeDistributionWindow5_i(Fl_Value_Slider*, void*);
  static void cb_degreeDistributionWindow5(Fl_Value_Slider*, void*);
  inline void cb_Fit2_i(Fl_Button*, void*);
  static void cb_Fit2(Fl_Button*, void*);
  inline void cb_Close1_i(Fl_Return_Button*, void*);
  static void cb_Close1(Fl_Return_Button*, void*);
  inline void cb_11_i(Fl_Button*, void*);
  static void cb_11(Fl_Button*, void*);
public:
  ExpressionWindow *expressionWindow;
private:
  inline void cb_OK8_i(Fl_Return_Button*, void*);
  static void cb_OK8(Fl_Return_Button*, void*);
  inline void cb_Cancelb_i(Fl_Button*, void*);
  static void cb_Cancelb(Fl_Button*, void*);
  inline void cb_12_i(Fl_Button*, void*);
  static void cb_12(Fl_Button*, void*);
public:
  ExportStatisticsWindow *exportStatistics;
private:
  inline void cb_Save3_i(Fl_Return_Button*, void*);
  static void cb_Save3(Fl_Return_Button*, void*);
  inline void cb_Cancelc_i(Fl_Button*, void*);
  static void cb_Cancelc(Fl_Button*, void*);
  inline void cb_exportStatisticsWindow_i(Fl_Round_Button*, void*);
  static void cb_exportStatisticsWindow(Fl_Round_Button*, void*);
  inline void cb_exportStatisticsWindow1_i(Fl_Round_Button*, void*);
  static void cb_exportStatisticsWindow1(Fl_Round_Button*, void*);
  inline void cb_exportStatisticsWindow2_i(Fl_Round_Button*, void*);
  static void cb_exportStatisticsWindow2(Fl_Round_Button*, void*);
  inline void cb_exportStatisticsWindow3_i(Fl_Value_Input*, void*);
  static void cb_exportStatisticsWindow3(Fl_Value_Input*, void*);
  inline void cb_exportStatisticsWindow4_i(Fl_Value_Input*, void*);
  static void cb_exportStatisticsWindow4(Fl_Value_Input*, void*);
  inline void cb_exportStatisticsWindow5_i(Fl_Round_Button*, void*);
  static void cb_exportStatisticsWindow5(Fl_Round_Button*, void*);
  inline void cb_exportStatisticsWindow6_i(Fl_Round_Button*, void*);
  static void cb_exportStatisticsWindow6(Fl_Round_Button*, void*);
  inline void cb_exportStatisticsWindow7_i(Fl_Round_Button*, void*);
  static void cb_exportStatisticsWindow7(Fl_Round_Button*, void*);
  inline void cb_exportStatisticsWindow8_i(Fl_Value_Input*, void*);
  static void cb_exportStatisticsWindow8(Fl_Value_Input*, void*);
  inline void cb_exportStatisticsWindow9_i(Fl_Value_Input*, void*);
  static void cb_exportStatisticsWindow9(Fl_Value_Input*, void*);
  inline void cb_exportStatisticsWindowa_i(Fl_Round_Button*, void*);
  static void cb_exportStatisticsWindowa(Fl_Round_Button*, void*);
  inline void cb_exportStatisticsWindowb_i(Fl_Round_Button*, void*);
  static void cb_exportStatisticsWindowb(Fl_Round_Button*, void*);
  inline void cb_exportStatisticsWindowc_i(Fl_Round_Button*, void*);
  static void cb_exportStatisticsWindowc(Fl_Round_Button*, void*);
  inline void cb_exportStatisticsWindowd_i(Fl_Value_Input*, void*);
  static void cb_exportStatisticsWindowd(Fl_Value_Input*, void*);
  inline void cb_exportStatisticsWindowe_i(Fl_Value_Input*, void*);
  static void cb_exportStatisticsWindowe(Fl_Value_Input*, void*);
  inline void cb_13_i(Fl_Button*, void*);
  static void cb_13(Fl_Button*, void*);
public:
  ExportTopologyWindow *exportTopologyWindow;
private:
  inline void cb_Save4_i(Fl_Return_Button*, void*);
  static void cb_Save4(Fl_Return_Button*, void*);
  inline void cb_Canceld_i(Fl_Button*, void*);
  static void cb_Canceld(Fl_Button*, void*);
  inline void cb_14_i(Fl_Button*, void*);
  static void cb_14(Fl_Button*, void*);
  inline void cb_exportTopologyWindow_i(Fl_Round_Button*, void*);
  static void cb_exportTopologyWindow(Fl_Round_Button*, void*);
  inline void cb_exportTopologyWindow1_i(Fl_Round_Button*, void*);
  static void cb_exportTopologyWindow1(Fl_Round_Button*, void*);
  inline void cb_exportTopologyWindow2_i(Fl_Round_Button*, void*);
  static void cb_exportTopologyWindow2(Fl_Round_Button*, void*);
  inline void cb_exportTopologyWindow3_i(Fl_Round_Button*, void*);
  static void cb_exportTopologyWindow3(Fl_Round_Button*, void*);
  inline void cb_exportTopologyWindow4_i(Fl_Round_Button*, void*);
  static void cb_exportTopologyWindow4(Fl_Round_Button*, void*);
};
#endif
